### PR TITLE
Implement Defense Mode Switch (TODO:  add it to the command line)

### PR DESCRIPTION
**Pull request by BaQs**
Request:

>  home
curl -H 'Host: apiieu.ezvizlife.com' -H 'sessionId: xxx' --data "groupId=-1&mode=1" 'https://apiieu.ezvizlife.com/v3/userdevices/v1/group/switchDefenceMode'
 away
curl -H 'Host: apiieu.ezvizlife.com' -H 'sessionId: xxx' --data "groupId=-1&mode=2" 'https://apiieu.ezvizlife.com/v3/userdevices/v1/group/switchDefenceMode'

Answer:

> {
	"meta": {
		"code": 200,
		"message": "操作成功",
		"moreInfo": null
	},
	"retMap": {
		"EXXXXXXX": "0",
		"DXXXXXXX": "0",
		"DXXXXXXX": "0",
		"DXXXXXXX": "0",
		"EXXXXXXX": "0",
		"DXXXXXXX": "0"
	}
}

- [ ]  TODO: add it to the command line

### CODE REVIEW

**Comment by BaQs** [comment]
@RenierM26 what do you think ?

This feature has been added few months ago in the iOS app, and enables/disables presence detection to all cameras at once.

I think it could be very usefull for the home assistant integration, wouldn't it ?

**Comment by RenierM26** [comment]
Hi BaQs, 

This change will break the detection sensibility logic for battery cameras. I do however see a better way to check switch types from the pagelist api. Will also not need rebuilding via a loop.

I was trying to detect the presence of this feature using the EXTstatus for more general support. - Doesn't work for your setup so my logic was flawed there.

**Comment by BaQs** [comment]
Indeed I tried to determine the compatibility of devices towards this feature.
I think there is no check in the app, the app just returns the status of the activation (in the returned json)

**Comment by BaQs** [comment]
doesn't help :(

>  $   pyezviz -u mail@xxxs.net -p "xxxx"   devices status
> local variable 'json_result' referenced before assignment

**Pull request merged**
